In [1]:
import numpy as np #task1 
import pandas as pd 

In [2]:
np.random.seed(101) #task2 
arr = np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [3]:
mat =  np.random.randint(0,100,500).reshape(100,5) #task 3
print(mat)

[[ 4 63 40 60 92]
 [64  5 12 93 40]
 [49 83  8 29 59]
 [34 44 72 19 10]
 [76 95 87  0 73]
 [ 8 62 36 83 99]
 [28 63  7 10 52]
 [56 38 73 52 18]
 [71 15 44  0 12]
 [17 75 79 97 93]
 [24 36 63 19 35]
 [30 10 60 20 27]
 [ 8 86 26 87 46]
 [47 54 86  9 45]
 [ 2 18 58 92 11]
 [10 94 35 28  3]
 [83 84 47 14 69]
 [60 69 51  6 88]
 [71 68 23 35 79]
 [98 67 82 57 77]
 [46  3 46 29 86]
 [21 21 81 23 94]
 [71 20 27 75  5]
 [49 86 89 63 82]
 [77  3 56 14 49]
 [87 52 13 47 49]
 [24 20 64 52 60]
 [47 29 60 53 11]
 [40 91 45 97 24]
 [36 38  9 52 67]
 [43  1 79 68 68]
 [61 18 51 14 28]
 [17 87 46 52 16]
 [70 71 84 10 62]
 [96 57 23 86 85]
 [26 76 66 54 17]
 [65 57 89  2 80]
 [50 66 88 79 93]
 [ 6 92 42 22 20]
 [25 97 54 71 72]
 [80 93 64 63 80]
 [38 45 35 25 95]
 [75 72 11 76 79]
 [50 22 59 66  1]
 [34 37 57 35 42]
 [44 49 31 79 85]
 [ 3 55 73 93 94]
 [99 40 54 88 94]
 [86 17 68 17 18]
 [60 83 82  7 67]
 [34 76 94 20 69]
 [73 59 34 69 25]
 [78 92 74 75 33]
 [ 9 43 20 82 30]
 [ 3 46 29 47 27]
 [81 71 25

In [4]:
df=pd.DataFrame(mat) #task 4 
df

0   1   2   3   4
0    4  63  40  60  92
1   64   5  12  93  40
2   49  83   8  29  59
3   34  44  72  19  10
4   76  95  87   0  73
..  ..  ..  ..  ..  ..
95  26  87  65  60  89
96  70  33  59  28  16
97  49  95  41  11  86
98  15  95  91  19  69
99   1  77  63  87  28

[100 rows x 5 columns]

In [5]:
df.columns=['f1','f2','f3','f4','label'] #task 5 
df

f1  f2  f3  f4  label
0    4  63  40  60     92
1   64   5  12  93     40
2   49  83   8  29     59
3   34  44  72  19     10
4   76  95  87   0     73
..  ..  ..  ..  ..    ...
95  26  87  65  60     89
96  70  33  59  28     16
97  49  95  41  11     86
98  15  95  91  19     69
99   1  77  63  87     28

[100 rows x 5 columns]

In [6]:
dp=pd.DataFrame(np.random.randint(0,100,200).reshape(50,4)) #task 6
dp.columns=['A','B','C','D']
dp

A   B   C   D
0   70   5   3  12
1   62  26  96  61
2   87  74  99  97
3   64  95   3  88
4   59  38  29  31
5   88  57   9  62
6   31  13  35  47
7    2  17  50  22
8   30  36  22  97
9   51  38  28   4
10   0  12  90   2
11   7  44  54  49
12  76  98   3  32
13  91  43   7  42
14  66   9   5  26
15  66  22  47  27
16  46  14  52  74
17  54   3  94  36
18  63  41  18  37
19  45  82  47  66
20  97  20   9  87
21  40  13  95  16
22  38  87  72  60
23  78  53  48  83
24  90  41  84  78
25  55  70  93  57
26  86  67   8  47
27  70  39  53   5
28  40  88  58  12
29  70   5  82   8
30  60  58  45  92
31  85  44  62  39
32  38  54  98  80
33  93  16  37  58
34  40  72  72  22
35  42  38  45  16
36  52  17  22  15
37  18  37  48   2
38   2  31  50  78
39  70  40  60  62
40  69  34  95  58
41   4  70  20  18
42  66  23  87  45
43  64   6  39  29
44  60  33  18  59
45  64  59  65  10
46  86  66  38  76
47  97  79   7  65
48  50  53   4  39
49   1   5  67  92